description: ""
version: 1
properties:
  auto_dependency: false
jobs:
- Ext_Databricks_1:
    spark_properties:
      spark_version: "7.2.x-hls-scala2.12"
parallel: 1
spark_properties:
  spark_version: "7.2.x-hls-scala2.12"
